openapi: 3.0.0
info:
  title: Todo Application API
  description: API for the Todo Full-Stack Web Application
  version: 1.0.0
  contact:
    name: Todo App Development Team

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://todo-app.example.com
    description: Production server

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  minLength: 8
                  description: User's password (minimum 8 characters)
                name:
                  type: string
                  minLength: 2
                  maxLength: 100
                  description: User's display name
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: User's unique identifier
                  email:
                    type: string
                    format: email
                    description: User's email address
                  name:
                    type: string
                    description: User's display name
                  created_at:
                    type: string
                    format: date-time
                    description: Account creation timestamp
        '400':
          description: Invalid input data
        '409':
          description: Email already exists

  /api/auth/login:
    post:
      summary: Login user
      description: Authenticates user and returns JWT token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT access token
                  refresh_token:
                    type: string
                    description: JWT refresh token
                  token_type:
                    type: string
                    default: bearer
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials

  /api/tasks:
    get:
      summary: Get user's tasks
      description: Retrieves all tasks for the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
    post:
      summary: Create a new task
      description: Creates a new task for the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  minLength: 2
                  maxLength: 100
                  description: Task title (2-100 characters)
                description:
                  type: string
                  maxLength: 1000
                  description: Optional task description (up to 1000 characters)
                completed:
                  type: boolean
                  default: false
                  description: Task completion status
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized - Invalid or missing JWT

  /api/tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieves a specific task by ID for the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '404':
          description: Task not found
    put:
      summary: Update a task
      description: Updates an existing task for the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 2
                  maxLength: 100
                  description: Task title (2-100 characters)
                description:
                  type: string
                  maxLength: 1000
                  description: Optional task description (up to 1000 characters)
                completed:
                  type: boolean
                  description: Task completion status
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized - Invalid or missing JWT
        '404':
          description: Task not found
    delete:
      summary: Delete a task
      description: Deletes a task for the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Invalid or missing JWT
        '404':
          description: Task not found

  /api/tasks/{id}/toggle:
    patch:
      summary: Toggle task completion status
      description: Toggles the completion status of a task
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '404':
          description: Task not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: User's unique identifier
        email:
          type: string
          format: email
          description: User's email address
        name:
          type: string
          description: User's display name
        avatar:
          type: string
          format: uri
          description: URL to user's avatar image
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp

    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Task's unique identifier
        title:
          type: string
          description: Task title (2-100 characters)
        description:
          type: string
          description: Optional task description (up to 1000 characters)
        completed:
          type: boolean
          description: Task completion status
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this task
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp